version: "3.1"

services:
    development:
        container_name: bff-gql-development
        build: .
        ports:
            - 8080:8080
            - 9229:9229
        command: /app/node_modules/.bin/nodemon -- --inspect=0.0.0.0 /app/src/index.js
        # command: /app/node_modules/.bin/nodemon /app/src/index.js
        # command: node --inspect=0.0.0.0 /app/src/index.js
        # command: node /app/src/index.js
        environment:
            - SERVER_PORT=8080
            - UNIT_SERVER_HOST=unit-api
            - UNIT_SERVER_PORT=80
        volumes:
            - ./build:/app/src
            - ./node_modules:/app/node_modules
        depends_on:
            - unit-api
        links:
            - unit-api

    gated-development:
        container_name: bff-gql-gated-development
        build: .
        ports:
            - 8080:8080
            - 9229:9229
        command: /app/node_modules/.bin/nodemon -- --inspect=0.0.0.0 /app/src/index.js
        # command: /app/node_modules/.bin/nodemon /app/src/index.js
        # command: node --inspect=0.0.0.0 /app/src/index.js
        # command: node /app/src/index.js
        environment:
            - SERVER_PORT=8080
            - UNIT_SERVER_HOST=gate-pep
            - UNIT_SERVER_PORT=80
        volumes:
            - ./build:/app/src
            - ./node_modules:/app/node_modules
        depends_on:
            - gate-pep
        links:
            - gate-pep

    gate-pep:
        container_name: bff-gql-development-gate-pep
        image: einarvalur/gate-pep:9498efa
        environment:
            - PROXY_PORT=80
            - FORWARD_URL=http://unit-api:80
            - JWT_SECRET=thisissomesecretornot
        depends_on:
            - unit-api

    unit-api:
        image: einarvalur/unit-api:12693b6
        container_name: bff-gql-unit-api
        depends_on:
            - bff-unit-api-database
        environment:
            - DB_HOST=bff-unit-api-database
            - DB_DATABASE=unit

    bff-unit-api-database:
        image: mongo
        container_name: bff-gql-unit-api-database
        restart: always
